-- MySQL Script generated by MySQL Workbench
-- 09/30/20 14:05:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clayey` DEFAULT CHARACTER SET utf8 ;
USE `clayey` ;

 DROP TABLE IF EXISTS `clayey`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `clayey`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


    
    
 DROP TABLE IF EXISTS `clayey`.`Produto` ;

CREATE TABLE IF NOT EXISTS `clayey`.`Produto` (
  `idProduto` INT NOT NULL,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `descProduto` VARCHAR(45) NOT NULL,
  `modoUsar` VARCHAR(45) NOT NULL,
  `composicao` VARCHAR(45) NOT NULL,
  `valorProduto` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


 DROP TABLE IF EXISTS `clayey`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `clayey`.`Pedido` (
  `idPedido` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `idCliente` INT ,
  `valorTotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `Pedido_idCliente_idx` (`idCliente` ASC),
  CONSTRAINT `Pedido_idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




DROP TABLE IF EXISTS `clayey`.`Item` ;

CREATE TABLE IF NOT EXISTS `clayey`.`Item` (
  `idProduto` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `qtde` INT NOT NULL,
  `valorItem` DECIMAL(10,2) NOT NULL,
  INDEX `Item_idProduto_idx` (`idProduto` ASC),
  INDEX `Item_idPedido_idx` (`idPedido` ASC),
  CONSTRAINT `Item_idProduto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Item_idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





insert into Cliente (idCliente,nomeCliente, email, senha) values
	(1,'cliente 1', 'cliente1@mail.com', '1234'),
    (2,'cliente 2', 'cliente2@mail.com', '1234'),
    (3,'cliente 3', 'cliente3@mail.com', '1234'),
    (4,'cliente 4', 'cliente4@mail.com', '1234');


select * from Cliente;

insert into Produto (idProduto,nomeProduto, descProduto, modoUsar,composicao,valorProduto) values
	(100,'argila branca', 'decricao argila branca', 'como usar argila branca', 'composição argila branca', 46.00),
	(101,'argila vermelha', 'decricao argila vermelha', 'como usar argila vermelha', 'composição argila vermelha', 46.00),
	(102,'alecrim', 'decricao alecrim', 'como usar alecrim', 'composição alecrim', 50.00),
	(103,'carvão ativado', 'decricao carvão ativado', 'como usar carvão ativado', 'composição carvão ativado', 50.00),
	(104,'amêndoas', 'decricao amêndoas', 'como usar amêndoas', 'composição amêndoas', 56.00);

select * from Produto;


insert into Pedido (idPedido, dataPedido, idCliente, valorTotal) values
	(1000, '2020-09-29', null, 100.00),
    (1001, '2020-09-30', null, 96.00),
    (1002, '2020-09-30', null, 46.00),
    (1003, '2020-09-30', null, 46.00)
	;
    
select * from pedido;

insert into Item (idProduto, idPedido, qtde, valorItem) values
	(100,1003, 1, 46.00);

 /* 
 UPDATE Pedido
 SET idCliente = 1
 WHERE idPedido = 1000;

   
select p.idPedido from Pedido p
inner join Cliente c on c.idCliente = p.idCliente
where p.idCliente = 1
group by p.idPedido ;

*/